### ISSUE TITLE
section names in html

### ISSUE THREAD

**Issue by rimmesbe** [jengels34/tea_cozy#1]
"mission" is a good name for this section. However "middle" and "bottom" are not good section names because they don't describe the section at all and also it adds an order dependency to the sections. Use more descriptive names like:
.tea-section
.location-section
something like that.

https://github.com/jengels34/tea_cozy/blob/master/index.html#L28-L35

**Comment by jengels34** [comment]
fixed middle and bottom, but not the 'top'
